### ISSUE TITLE
Add windows support

### ISSUE THREAD

**Issue by daniel-lightlytics** [trakBan/spongebob-cli#25]
Installing on windows works fine
When selecting episode an exception is raised:
```
.....
What episode do you want to watch? (type a number by the right side): 1
Now playing: https://www.megacartoons.net/video/SpongeBob-SquarePants-Help-Wanted.mp4

Traceback (most recent call last):
  File "C:\Users\User\spongebob-cli\spongebob-cli", line 214, in <module>
    Play(real)
  File "C:\Users\User\spongebob-cli\spongebob-cli", line 55, in Play
    subprocess.run(["mpv", DirectLink])
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by daniel-lightlytics** [comment]
My bad, installing MPV through chocolatey fixed this :)

**Comment by kevinfengcs88** [comment]
I had the same problem, installing with chocolatey didn't work the first time, but I just did a clean uninstall and reinstall (running the script option that comes up each time) until nothing failed and then I was able to watch the episodes through mpv; much cooler than browser :3
