### ISSUE TITLE
only one episode is listed

### ISSUE THREAD

**Issue by isidroas** [trakBan/spongebob-cli#38]
```
$ ./spongebob-cli
+-------------+--------+
|   Episodes  | Number |
+-------------+--------+
| Help Wanted |   0    |
+-------------+--------+
What episode do you want to watch?: 0
Traceback (most recent call last):
  File "/tmp/spongebob-cli/./spongebob-cli", line 189, in <module>
    main(args)
  File "/tmp/spongebob-cli/./spongebob-cli", line 135, in main
    video = videoSource(episodesUrls[userInput()])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/spongebob-cli/./spongebob-cli", line 56, in videoSource
    return soupRelative.find("input", {"name": "main_video_url"})["value"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

**Comment by trakBan** [comment]
I will look into this throughout the week

**Comment by trakBan** [comment]
The website changed the layout making it impossible for the program to scrape the episodes, I have made an temporary fix, listing only the first 95 episodes.
